### ISSUE TITLE
alphabetical index for winnowing

### ISSUE THREAD

**Issue by srearl** [BLE-LTER/QUDT_Browser#2]
@twhiteaker - Cannot tell you how much our WG appreciates this tool that you built, it is so helpful and we use it a lot! At the risk of being a choosy beggar, if it would not require too much time and effort, could you add somewhere on the page an alphabetical index such that one could see with a click all the units that start with, for example, the letter M? Apologies that my JS is too limited to help.

**Comment by twhiteaker** [comment]
That functionality isn't built in to datatables, but it seems possible to add it using
https://datatables.net/blog/2014-08-26
or
https://www.gyrocode.com/articles/jquery-datatables-alphabetical-search/

I don't know when I could get to it though. I'll send you a DM about that.

**Comment by twhiteaker** [comment]
Fixed in 55ab42e79461cd7040c35c3f7ab3da6b284f7723

**Comment by srearl** [comment]
Awesome, thanks so much, @twhiteaker !
